package html

const (
	// _ string = ""
	_all           string = "all"
	_bottomMargin  string = "bottomMargin"
	_convert       string = "convert"
	_fragments     string = "fragments"
	_height        string = "height"
	_html          string = "html"
	_image         string = "image"
	_images        string = "images"
	_import        string = "import"
	_json          string = "json"
	_keywords      string = "keywords"
	_leftMargin    string = "leftMargin"
	_ocr           string = "ocr"
	_ocrEngineLang string = "ocrEngineLang"
	_outPath       string = "outPath"
	_pdf           string = "pdf"
	_plain         string = "plain"
	_resolution    string = "resolution"
	_rightMargin   string = "rightMargin"
	_sourceURL     string = "sourceUrl"
	_summ          string = "summ"
	_topMargin     string = "topMargin"
	_translate     string = "translate"
	_width         string = "width"
	_xPath         string = "xPath"
	_xps           string = "xps"
)
